include:
  - dataset_common.yaml
model:
  type: gbdt
  gbdt:
    library: lightgbm
    params:
      n_estimators: 1200
      learning_rate: 0.03
      num_leaves: 63
      subsample: 0.8
      colsample_bytree: 0.8
      max_depth: -1
preproc:
  aggregate_to_year: mean_sum  # mean of means, sum of precip by default
  include_prev_year_yield: true
featureset: all
