include:
  - elasticnet_enhanced.yaml
name: wheat_random_forest
model:
  type: random_forest
  random_forest:
    n_estimators: 500
    max_depth: null
    min_samples_leaf: 3
    n_jobs: -1
    random_state: 1337
